# Generated by Django 2.1 on 2018-09-07 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, null=True, verbose_name='姓名')),
                ('password', models.CharField(max_length=50, null=True, verbose_name='用户密码')),
                ('mailbox', models.EmailField(max_length=20, null=True, verbose_name='邮箱')),
                ('phone', models.IntegerField(max_length=20, null=True, verbose_name='手机号码')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True, verbose_name='创建时间')),
            ],
        ),
    ]
